name: Windows

on:
  push:
    tags:
      - V*
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  TARGET_NAME: GnssView

jobs:
  build:
    name: Build on Win2022
    runs-on: windows-2022

    steps:
    - name: Install
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.8.0
        modules: 'qtcharts qtserialport'
        arch: win64_msvc2022_64
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      shell: cmd
      run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      shell: cmd
      run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

    - name: Package
      shell: pwsh
      run: |
        windeployqt --no-translations --compiler-runtime build\Release\${env:TARGET_NAME}'.exe'

    - name: Installer
      uses: joncloud/makensis-action@v3.7


    - name: Release
      if: startsWith(github.event.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.TARGET_NAME }}_setup.exe
        asset_name: ${{ env.TARGET_NAME }}_win_${{ github.ref_name }}.exe
        tag: ${{ github.ref }}
        overwrite: true
